/**
 * Modified by NewFlow Team
 * Original work: Copyright (c) 2019-2024, Jan Oberhauser (n8n)
 * Modified work: Copyright (c) 2024, NewFlow Team
 *
 * This file is part of NewFlow, a modified version of n8n.
 * License: Sustainable Use License (see LICENSE.md)
 */

// This file was generated by lezer-generator. You probably shouldn't edit it.
export const Whitespace = 1,
	LineComment = 2,
	BlockComment = 3,
	String = 4,
	Number = 5,
	Bool = 6,
	Null = 7,
	ParenL = 8,
	ParenR = 9,
	BraceL = 10,
	BraceR = 11,
	BracketL = 12,
	BracketR = 13,
	Semi = 14,
	Dot = 15,
	Operator = 16,
	Punctuation = 17,
	SpecialVar = 18,
	Identifier = 19,
	QuotedIdentifier = 20,
	Keyword = 21,
	Type = 22,
	Bits = 23,
	Bytes = 24,
	Builtin = 25,
	Function = 26,
	Script = 27;
