#!/bin/bash

# 安装 NewRAG
# 前提：newrag-main/ 已通过 scripts/clone_modules.sh 从 GitHub 克隆

# 兼容 Homebrew (Apple Silicon) 和系统安装
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
unset NVM_DIR NVM_BIN NVM_INC

# 如果 log_info 未定义，定义简单的 fallback (兼容 start_all.sh)
if ! command -v log_info &> /dev/null; then
    log_info() { echo "ℹ️  $1"; }
    log_warn() { echo "⚠️  $1"; }
    log_error() { echo "❌ $1"; }
    log_success() { echo "✅ $1"; }
fi

# 加载平台 .env（用于配置覆盖）
load_platform_env() {
    local env_file="$PROJECT_ROOT/.env"
    if [ -f "$env_file" ]; then
        set -a
        source "$env_file"
        set +a
    fi
}

# 生成 NewRAG 配置文件（从 config.example.yaml + 平台 .env 覆盖）
generate_newrag_config() {
    local target_dir=$1
    local config_file="$target_dir/config.yaml"
    local example_file="$target_dir/config.example.yaml"

    if [ -f "$config_file" ]; then
        log_info "config.yaml 已存在，跳过生成"
        return 0
    fi

    if [ ! -f "$example_file" ]; then
        log_warn "config.example.yaml 不存在，跳过配置生成"
        return 0
    fi

    log_info "从 config.example.yaml 生成 config.yaml（应用平台端口和凭据）..."
    cp "$example_file" "$config_file"

    # 平台约定端口: backend=8080, frontend=3000, mcp=3001
    sed -i '' 's/port: 8081/port: 8080/' "$config_file" 2>/dev/null || true
    sed -i '' 's/frontend_port: 3001/frontend_port: 3000/' "$config_file" 2>/dev/null || true
    sed -i '' 's/port: 2999/port: 3001/' "$config_file" 2>/dev/null || true

    # ES 认证（从平台 .env 注入）
    if [ -n "$ELASTIC_PASSWORD" ]; then
        sed -i '' "s/username: \"\"/username: \"elastic\"/" "$config_file" 2>/dev/null || true
        sed -i '' "s/password: \"\"/password: \"$ELASTIC_PASSWORD\"/" "$config_file" 2>/dev/null || true
    fi

    log_success "config.yaml 已生成"
}

# 生成 NewRAG .env 文件
generate_newrag_env() {
    local target_dir=$1
    local env_file="$target_dir/.env"

    if [ -f "$env_file" ]; then
        log_info ".env 已存在，跳过生成"
        return 0
    fi

    log_info "生成 NewRAG .env 文件..."
    cat > "$env_file" <<ENVEOF
# Auto-generated by platform installer
DATABASE_URL=sqlite:///data/documents.db
ES_HOST=http://localhost:${ES_PORT_1:-9200}
ES_USERNAME=${ES_SECURITY_ENABLED:+elastic}
ES_PASSWORD=${ELASTIC_PASSWORD:-}
WEB_HOST=0.0.0.0
WEB_PORT=8080
MINIO_ENABLED=${MINIO_ENABLED:-true}
MINIO_ENDPOINT=localhost:${MINIO_API_PORT:-9000}
MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin123}
MINIO_BUCKET=rag-bucket
MINIO_SECURE=false
MINIO_PUBLIC_URL=http://localhost:${MINIO_API_PORT:-9000}
EMBEDDING_API_URL=http://localhost:1234/v1
EMBEDDING_API_KEY=lm-studio
VISION_API_URL=http://localhost:1234/v1
VISION_API_KEY=lm-studio
ENVEOF
    log_success ".env 已生成"
}

run_step() {
    local force_install=$1
    local PROJECT_ROOT
    PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
    local target_dir="$PROJECT_ROOT/newrag-main"

    log_info "检查 NewRAG 安装状态..."

    # 0. 目录必须已存在（由 clone_modules.sh 克隆）
    if [ ! -d "$target_dir" ]; then
        log_error "NewRAG 目录不存在: $target_dir"
        log_error "请先运行: bash scripts/clone_modules.sh"
        return 1
    fi

    # 加载平台环境变量
    load_platform_env

    cd "$target_dir" || return 1

    # 1. 配置 Python 后端
    if [ -d ".venv" ] && [ -f ".venv/bin/python" ] && [ "$force_install" != "true" ]; then
         log_info "Python 环境已存在，跳过配置"
    else
        log_info "配置 NewRAG 后端 (uv sync)..."
        if ! command -v uv &> /dev/null; then
            log_error "未找到 uv 命令"
            cd "$PROJECT_ROOT"
            return 1
        fi

        export UV_HTTP_TIMEOUT=300

        if [ ! -d ".venv" ]; then
            log_info "创建 Python 3.11 虚拟环境..."
            if ! uv venv .venv --python 3.11; then
                log_error "创建虚拟环境失败"
                cd "$PROJECT_ROOT"
                return 1
            fi
        fi

        log_info "安装 Python 依赖..."
        if uv sync; then
            log_success "NewRAG 后端依赖安装完成"
        else
            log_warn "官方源下载失败，尝试切换到清华镜像源..."
            export UV_INDEX_URL="https://pypi.tuna.tsinghua.edu.cn/simple"
            if uv sync; then
                log_success "NewRAG 后端依赖安装完成 (镜像源)"
            else
                log_error "NewRAG 后端依赖安装失败"
                cd "$PROJECT_ROOT"
                return 1
            fi
        fi
    fi

    # 2. 配置前端 (npm install，开发模式不需要 build)
    if [ -d "frontend" ]; then
        if [ -d "frontend/node_modules" ] && [ "$force_install" != "true" ]; then
            log_info "前端依赖已安装，跳过"
        else
            log_info "配置 NewRAG 前端..."
            cd frontend

            for ts_file in tsconfig.app.json tsconfig.node.json tsconfig.json; do
                if [ -f "$ts_file" ]; then
                    sed -i '' 's/"noUnusedLocals": true/"noUnusedLocals": false/g' "$ts_file" 2>/dev/null || true
                    sed -i '' 's/"noUnusedParameters": true/"noUnusedParameters": false/g' "$ts_file" 2>/dev/null || true
                fi
            done

            if ! command -v npm &> /dev/null; then
                log_error "未找到 npm 命令"
                cd "$PROJECT_ROOT"
                return 1
            fi

            if ! npm install; then
                log_error "前端依赖安装失败"
                cd "$PROJECT_ROOT"
                return 1
            fi

            log_success "前端依赖安装完成"
            cd ..
        fi
    else
        log_warn "未找到 frontend 目录，跳过前端配置"
    fi

    # 3. 配置 MCP (npm install & build)
    if [ -d "newrag-mcp" ]; then
        if [ -d "newrag-mcp/node_modules" ] && [ -d "newrag-mcp/dist" ] && [ "$force_install" != "true" ]; then
            log_info "MCP 依赖已安装且已构建，跳过"
        else
            log_info "配置 NewRAG MCP..."
            cd newrag-mcp
            if ! npm install; then
                log_error "MCP 依赖安装失败"
                cd "$PROJECT_ROOT"
                return 1
            fi
            if ! npm run build; then
                log_error "MCP 构建失败"
                cd "$PROJECT_ROOT"
                return 1
            fi
            cd ..
        fi
    else
        log_warn "未找到 newrag-mcp 目录，跳过 MCP 配置"
    fi

    # 4. 生成配置文件
    generate_newrag_config "$target_dir"
    generate_newrag_env "$target_dir"

    # 5. 确保关键目录存在（必须在认证初始化之前，SQLite 需要 data/ 目录）
    mkdir -p logs data uploads web/static/processed_docs

    # 6. 初始化认证系统
    if [ -f "scripts/init_auth_system.py" ]; then
        log_info "初始化认证系统..."
        if ! uv run scripts/init_auth_system.py; then
            log_error "认证系统初始化失败，请检查日志"
            cd "$PROJECT_ROOT"
            return 1
        fi
        # 验证 admin 用户已写入
        local db_file="data/documents.db"
        if command -v sqlite3 &>/dev/null && [ -f "$db_file" ]; then
            local user_count
            user_count=$(sqlite3 "$db_file" "SELECT COUNT(*) FROM users;" 2>/dev/null || echo "0")
            if [ "$user_count" = "0" ]; then
                log_error "认证系统初始化后 users 表为空，初始化可能未成功"
                cd "$PROJECT_ROOT"
                return 1
            fi
            log_success "认证系统验证通过（用户数: $user_count）"
        fi
    fi

    cd "$PROJECT_ROOT"

    log_success "NewRAG 准备就绪"
    return 0
}

if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then
    run_step "$@"
fi
